// <auto-generated />
using System;
using Clinic_WebAppv2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic_WebAppv2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Clinic_WebAppv2.Models.Consultation", b =>
                {
                    b.Property<int>("consultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("consultID"));

                    b.Property<DateTime>("consultDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("diagnosis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("docID")
                        .HasColumnType("int");

                    b.Property<int>("patID")
                        .HasColumnType("int");

                    b.Property<string>("prescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("consultID");

                    b.HasIndex("docID");

                    b.HasIndex("patID");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("Clinic_WebAppv2.Models.Doctor", b =>
                {
                    b.Property<int>("docID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("docID"));

                    b.Property<string>("docAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("docFName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("docLName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("docSpecial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("docID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Clinic_WebAppv2.Models.Patient", b =>
                {
                    b.Property<int>("patID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("patID"));

                    b.Property<DateTime>("patBDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("patFName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("patLName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("patTelNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("patID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Clinic_WebAppv2.Models.Consultation", b =>
                {
                    b.HasOne("Clinic_WebAppv2.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("docID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_WebAppv2.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("patID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
